### PR TITLE
Fix compiler warnings on linux

### LINKED ISSUE #2: build warning
From our builder image:

```
[15:58:02][Step 2/3] # github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix
[15:58:02][Step 2/3] In file included from wrap-common.c:1:
[15:58:02][Step 2/3] In file included from vendor/github.com/knz/go-libedit/unix/src/libedit-common.c:1:
[15:58:02][Step 2/3] vendor/github.com/knz/go-libedit/unix/src/c-libedit/common.c:371:21: warning: passing 'wint_t *' (aka 'unsigned int *') to parameter of type 'wchar_t *' (aka 'int *') converts between pointers to integer types with different sign [-Wpointer-sign]
[15:58:02][Step 2/3] vendor/github.com/knz/go-libedit/unix/src/c-libedit/histedit.h:267:37: note: passing argument to parameter here
```

Doesn't seem to be causing any harm, but would be nice to clean up if there's an easy fix!

### PR DESCRIPTION
**Pull request by benesch**
Fix #2.

---

I realize this came from upstream, but, ¯\_(ツ)_/¯ , it seems broken.

### CODE REVIEW

**Review by knz — APPROVED** [review]
Have you tried `refresh.sh` to see if there was any upstream patch available?

Also perhaps you should file a patch upstream too.

**Comment by benesch** [comment]
No upstream patch available, AFAICT. At least, the code here still looks the same: https://anonscm.debian.org/cgit/collab-maint/libedit.git/tree/src/common.c (I don't have a Linux box handy to test on.)

> Also perhaps you should file a patch upstream too.

Upstream appears to be NetBSD—any suggestions for getting a NetBSD VM? I just spent an hour trying to get something running on my laptop via VirtualBox and on EC2 but neither worked.

**Comment by knz** [comment]
> Upstream appears to be NetBSD

Yes and there are cross-updates across BSDs too.

I'd say submit a bug fix + proposed patch on both the NetBSD and FreeBSD
issue trackers.

Don't bother downloading the sources. Just check manually your diff is
relevant for http://cvsweb.netbsd.org/bsdweb.cgi/src/lib/libedit/ and
https://github.com/freebsd/freebsd/tree/master/lib/libedit and mention
the file/linenos in the issue reports:

https://bugs.freebsd.org/bugzilla/enter_bug.cgi

http://www.netbsd.org/cgi-bin/sendpr.cgi?gndb=netbsd

**Comment by benesch** [comment]
Alright, filed: https://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=53058

**Pull request merged**
